name: Laravel

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Set up PHP
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          extensions: xdebug

      - uses: actions/checkout@v4

      # Step 2: Copy .env file if not already present
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      # Step 3: Install Composer Dependencies
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      # Step 4: Generate the application key
      - name: Generate key
        run: php artisan key:generate

      # Step 5: Set directory permissions
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      # Step 6: Create SQLite database (for testing)
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite

      # Step 7: Run Tests and Generate Reports (Unit + Coverage)
      - name: Run Tests and Generate Reports (Unit + Coverage)
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: |
          # Run tests and generate both XML and HTML reports
          php artisan test --coverage-xml=storage/test-coverage/coverage.xml --coverage-html=storage/test-coverage/html

      # Step 8: Upload PHPUnit XML Coverage Report
      - name: Upload PHPUnit XML Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: phpunit-coverage-xml
          path: storage/test-coverage/coverage.xml
          retention-days: 3

      # Step 9: Upload PHPUnit HTML Coverage Report
      - name: Upload PHPUnit HTML Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: phpunit-coverage-html
          path: storage/test-coverage/html/*
          retention-days: 3

      # Step 10: Execute tests (Unit and Feature tests) via PHPUnit/Pest
      - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: php artisan test --coverage-text --coverage-clover=coverage.xml

  deploy:
    runs-on: ubuntu-latest
    needs: laravel-tests # Ensure deployment only happens after tests pass

    steps:
      # Step 1: Set up SSH key with passphrase for deployment
      # Step 1: Set up SSH key with passphrase for deployment
      - name: Set up SSH key with passphrase
        run: |
          # Start the SSH agent
          eval $(ssh-agent -s)

          # Add the private key to the agent using the passphrase from secrets
          echo "$SSH_PRIVATE_KEY" | ssh-add - <<< "$SSH_PASSPHRASE"

        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}

      # Step 2: Deploy to Server via SSH
      - name: Deploy to Server via SSH
        run: |
          ssh -o StrictHostKeyChecking=no -p 65002 u300028099@195.35.62.16 << 'EOF'
            # Navigate to your project directory
            cd /home/u300028099/domains/azikasyahputra.com/public_html/control-version

            # Pull the latest code from the 'main' branch
            git pull origin main

            # Check if the vendor directory exists or composer.json has changed
            if [ ! -d "vendor" ] || [ $(git diff --name-only HEAD~1 HEAD | grep "composer.json") ]; then
              echo "Either vendor directory not found or composer.json has changed, running composer install"
              composer install --no-dev --optimize-autoloader
            else
              echo "Vendor directory exists and composer.json has not changed, skipping composer install"
            fi

            # Run any database migrations
            php artisan migrate --force

            # Cache configuration and routes
            php artisan config:cache
            php artisan route:cache

            # Optimize the application
            php artisan optimize
          EOF
