name: Laravel CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  control-version-tests:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          extensions: sqlite, pdo_sqlite
          coverage: xdebug

      # Step 3: Cache Composer dependencies
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      # Step 4: Install Composer Dependencies
      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress

      # Step 5: Prepare Laravel Application
      - name: Prepare Application
        run: |
          php -r "file_exists('.env') || copy('.env.example', '.env');"
          php artisan key:generate

      # Step 6: Run Tests & Generate Reports
      - name: Run Tests & Generate Reports
        run: php artisan test --log-junit junit.xml --coverage-clover=coverage.clover.xml --coverage-html=storage/logs/coverage

      # Step 7: Generate HTML Test Report Summary
      # This new step reads the junit.xml file and creates a user-friendly summary.
      - name: Generate HTML Test Report Summary
        uses: dorny/test-reporter@v1
        if: success() || failure() # run this step even if tests fail
        with:
          name: Unit Test Results
          path: junit.xml
          reporter: jest-junit # This reporter creates a nice summary view

      # Step 8: Upload Clover XML Coverage Report
      - name: Upload Clover XML Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-xml
          path: coverage.clover.xml
          retention-days: 3

      # Step 9: Upload HTML Coverage Report
      - name: Upload HTML Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-html
          path: storage/logs/coverage
          retention-days: 3

  deploy:
    runs-on: ubuntu-latest
    needs: control-version-tests
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Deploy to Production Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/u300028099/domains/azikasyahputra.com/public_html/control-version
            git pull origin main

            if git diff --name-only HEAD~1 HEAD | grep -q "composer.lock"; then
              echo "composer.lock has changed, running composer install."
              composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev
            else
              echo "composer.lock has not changed, skipping composer install."
            fi

            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan event:cache
